import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { User, Upload, Loader, AlertCircle, Sparkles } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuthStore } from '../../stores/authStore';
import toast from 'react-hot-toast';

interface CompleteProfileModalProps {
  isOpen: boolean;
  currentUsername: string;
  currentAvatarUrl?: string | null;
  currentBio?: string | null;
  userId: string;
  onClose?: () => void;
}

const CompleteProfileModal: React.FC<CompleteProfileModalProps> = ({
  isOpen,
  currentAvatarUrl,
  currentBio,
  userId,
  onClose
}) => {
  const { t } = useTranslation();
  const [username, setUsername] = useState('');
  const [bio, setBio] = useState(currentBio || '');
  const [avatar, setAvatar] = useState<File | null>(null);
  const [avatarPreview, setAvatarPreview] = useState<string | null>(currentAvatarUrl || null);
  const [isLoading, setIsLoading] = useState(false);
  const [usernameError, setUsernameError] = useState<string | null>(null);
  const [isClosing, setIsClosing] = useState(false);

  useEffect(() => {
    if (currentAvatarUrl) {
      setAvatarPreview(currentAvatarUrl);
    }
    if (currentBio) {
      setBio(currentBio);
    }
  }, [currentAvatarUrl, currentBio]);

  const isUsernameValid = (value: string): boolean => {
    if (!value || value.trim() === '') {
      return false;
    }
    const autoGeneratedPattern = /^user_[a-zA-Z0-9]+$/i;
    if (autoGeneratedPattern.test(value.trim())) {
      return false;
    }
    if (value.trim().length < 3) {
      return false;
    }
    return true;
  };

  const validateUsername = (value: string): string | null => {
    if (!value || value.trim() === '') {
      return t('completeProfile.usernameRequired');
    }
    const autoGeneratedPattern = /^user_[a-zA-Z0-9]+$/i;
    if (autoGeneratedPattern.test(value.trim())) {
      return t('completeProfile.usernameCannotBeAutoGenerated');
    }
    if (value.trim().length < 3) {
      return t('completeProfile.usernameTooShort');
    }
    return null;
  };

  const handleUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setUsername(value);
    setUsernameError(validateUsername(value));
  };

  const handleAvatarChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const file = e.target.files[0];

      const validFileTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
      if (!validFileTypes.includes(file.type)) {
        toast.error(t('profile.unsupportedFileType'));
        return;
      }

      if (file.size > 5 * 1024 * 1024) {
        toast.error(t('profile.imageTooLarge'));
        return;
      }

      setAvatar(file);
      const objectUrl = URL.createObjectURL(file);
      setAvatarPreview(objectUrl);
    }
  };

  const uploadAvatar = async (): Promise<string | null> => {
    if (!avatar || !userId) return null;

    try {
      const fileExt = avatar.name.split('.').pop();
      const fileName = `${userId}-${Date.now()}.${fileExt}`;
      const filePath = `avatars/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('avatars')
        .upload(filePath, avatar, {
          cacheControl: '3600',
          upsert: false
        });

      if (uploadError) {
        throw uploadError;
      }

      const { data } = supabase.storage
        .from('avatars')
        .getPublicUrl(filePath);

      return data.publicUrl;
    } catch (error) {
      console.error('Error uploading avatar:', error);
      toast.error(t('profile.errorUploadingAvatar'));
      return null;
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const validationError = validateUsername(username);
    if (validationError) {
      setUsernameError(validationError);
      return;
    }

    try {
      setIsLoading(true);

      let avatarUrl = currentAvatarUrl;
      if (avatar) {
        const uploadedUrl = await uploadAvatar();
        if (uploadedUrl) {
          avatarUrl = uploadedUrl;
        }
      }

      const { error: updateError } = await supabase
        .from('users')
        .update({
          username: username.trim(),
          bio: bio.trim() || null,
          avatar_url: avatarUrl,
          is_profile_completed: true
        })
        .eq('id', userId);

      if (updateError) {
        console.error('Error updating profile:', updateError);
        throw updateError;
      }

      const checkSession = useAuthStore.getState().checkSession;
      await checkSession();

      toast.success(t('completeProfile.profileCompletedSuccess'));

      setIsClosing(true);
      setTimeout(() => {
        onClose?.();
      }, 300);

    } catch (error) {
      console.error('Error completing profile:', error);
      toast.error(t('completeProfile.errorCompletingProfile'));
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen || (isClosing && !onClose)) return null;

  const canSubmit = isUsernameValid(username) && !isLoading;

  return (
    <div className={`fixed inset-0 z-[100] flex items-center justify-center transition-opacity duration-300 ${isClosing ? 'opacity-0' : 'opacity-100'}`}>
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" />

      <div className={`relative w-full max-w-md mx-4 bg-white dark:bg-dark-100 rounded-2xl shadow-2xl overflow-hidden transition-all duration-300 ${isClosing ? 'opacity-0 scale-95' : 'animate-in fade-in zoom-in'}`}>
        <div className="bg-gradient-to-r from-primary-600 to-primary-700 px-6 py-8 text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-white/20 rounded-full mb-4">
            <Sparkles className="h-8 w-8 text-white" />
          </div>
          <h2 className="text-2xl font-heading font-bold text-white mb-2">
            {t('completeProfile.welcomeTitle')}
          </h2>
          <p className="text-primary-100">
            {t('completeProfile.welcomeSubtitle')}
          </p>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-6">
          <div>
            <label htmlFor="modal-username" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('completeProfile.chooseUsername')} <span className="text-error-500">*</span>
            </label>
            <input
              type="text"
              id="modal-username"
              value={username}
              onChange={handleUsernameChange}
              className={`w-full bg-gray-100 dark:bg-dark-200 border rounded-lg px-4 py-3 text-gray-900 dark:text-white focus:outline-none focus:ring-2 transition-colors ${
                usernameError
                  ? 'border-error-500 focus:ring-error-500'
                  : 'border-gray-300 dark:border-gray-700 focus:ring-primary-500'
              }`}
              placeholder={t('completeProfile.usernamePlaceholder')}
              disabled={isLoading}
              autoFocus
            />
            {usernameError && (
              <div className="flex items-center mt-2 text-error-500 text-sm">
                <AlertCircle className="h-4 w-4 mr-1.5 flex-shrink-0" />
                <span>{usernameError}</span>
              </div>
            )}
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
              {t('completeProfile.usernameHelp')}
            </p>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('completeProfile.profilePhoto')} <span className="text-gray-400">({t('common.optional')})</span>
            </label>
            <div className="flex items-center space-x-4">
              <div className="w-16 h-16 rounded-full bg-gray-200 dark:bg-dark-200 overflow-hidden flex items-center justify-center flex-shrink-0">
                {avatarPreview ? (
                  <img src={avatarPreview} alt="Avatar" className="w-full h-full object-cover" />
                ) : (
                  <User className="h-8 w-8 text-gray-400" />
                )}
              </div>
              <div className="flex-1">
                <label className="cursor-pointer bg-gray-200 dark:bg-dark-200 hover:bg-gray-300 dark:hover:bg-dark-300 text-gray-700 dark:text-white px-4 py-2 rounded-lg transition-colors inline-flex items-center text-sm">
                  <Upload className="h-4 w-4 mr-2" />
                  {avatarPreview ? t('profile.changePhoto') : t('profile.addPhoto')}
                  <input
                    type="file"
                    onChange={handleAvatarChange}
                    className="hidden"
                    accept="image/jpeg, image/png, image/gif, image/webp"
                    disabled={isLoading}
                  />
                </label>
                <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                  {t('profile.imageFormatsAndSize')}
                </p>
              </div>
            </div>
          </div>

          <div>
            <label htmlFor="modal-bio" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('completeProfile.aboutYou')} <span className="text-gray-400">({t('common.optional')})</span>
            </label>
            <textarea
              id="modal-bio"
              value={bio}
              onChange={(e) => setBio(e.target.value)}
              className="w-full bg-gray-100 dark:bg-dark-200 border border-gray-300 dark:border-gray-700 rounded-lg px-4 py-3 text-gray-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-primary-500 min-h-[80px] resize-none"
              placeholder={t('completeProfile.bioPlaceholder')}
              disabled={isLoading}
              maxLength={500}
            />
            <p className="text-xs text-gray-500 dark:text-gray-400 mt-1 text-right">
              {bio.length}/500
            </p>
          </div>

          <button
            type="submit"
            disabled={!canSubmit}
            className="w-full bg-primary-600 hover:bg-primary-700 disabled:bg-primary-600/50 disabled:cursor-not-allowed text-white font-medium py-3 px-4 rounded-lg transition-colors flex items-center justify-center"
          >
            {isLoading ? (
              <>
                <Loader className="h-5 w-5 mr-2 animate-spin" />
                {t('completeProfile.saving')}
              </>
            ) : (
              <>
                <Sparkles className="h-5 w-5 mr-2" />
                {t('completeProfile.letsGo')}
              </>
            )}
          </button>

          <p className="text-xs text-center text-gray-500 dark:text-gray-400">
            {t('completeProfile.editLaterNote')}
          </p>
        </form>
      </div>
    </div>
  );
};

export default CompleteProfileModal;
